# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CỬA HÀNG ĐTDĐ ĐỨC NGỌC APPLE
email: chaudanghuy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  điện thoại iphone, iphone, iphone 7, apple iphone 6s, apple ipad air, ipad pro
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#sidebar
default-image: webjeda-logo-big.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: Đức Ngọc Apple
copyright:
   name: Đức Ngọc Apple
   link: 'https://www.facebook.com/ducngocapple?fref=ts'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics: UA-46158141-1

# Comments
disqus-shortname: ducngocapple

# logo
favicon: favicon.gif

#social
facebook: http://facebook.com/ducngoco2
quora: http://quora.com/ducngoco2
twitter: http://twitter.com/@ducngoco2
github: http://github.com/ducngoco2

#facebook like box
fb-app-id: 549480635219583
fb-page-url: https://www.facebook.com/ducngoco2/
fb-page-title: ĐTDĐ Đức Ngọc Apple

# Sass style
sass:
  style: compressed

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
